"""add used to RefreshToken

Revision ID: 4a497a351b83
Revises: 76855f6621b9
Create Date: 2026-04-05 03:49:48.820794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a497a351b83'
down_revision: Union[str, Sequence[str], None] = '76855f6621b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('used', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_token', 'used')
    # ### end Alembic commands ###
