"""add bybit credentials

Revision ID: c0ecec34fb5a
Revises: 4a497a351b83
Create Date: 2026-04-09 23:00:01.371097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ecec34fb5a'
down_revision: Union[str, Sequence[str], None] = '4a497a351b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bybit_api_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('api_secret', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bybit_api_credentials_api_key'), 'bybit_api_credentials', ['api_key'], unique=False)
    op.create_index(op.f('ix_bybit_api_credentials_api_secret'), 'bybit_api_credentials', ['api_secret'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bybit_api_credentials_api_secret'), table_name='bybit_api_credentials')
    op.drop_index(op.f('ix_bybit_api_credentials_api_key'), table_name='bybit_api_credentials')
    op.drop_table('bybit_api_credentials')
    # ### end Alembic commands ###
