"""add trade and portfolio tables

Revision ID: e25f5c2c5617
Revises: c0ecec34fb5a
Create Date: 2026-04-10 16:32:40.772683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25f5c2c5617'
down_revision: Union[str, Sequence[str], None] = 'c0ecec34fb5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.String(length=50), nullable=False),
    sa.Column('position_id', sa.String(length=50), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.Enum('buy', 'sell', name='tradedirection'), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('close_time', sa.String(length=50), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('swap', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('profit', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('leverage', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
